name: Generate PDF

on: push

jobs:
  generate:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker://pandoc/latex:2.9
        run: make pdf
      - uses: actions/upload-artifact@master
        with:
          name: thesis
          path: output/thesis.pdf
